export const COLONY_BUILDING_IDS = {
  HEADQUARTERS: [1, 82010100, 82010300],
  LEGACY_SHIPYARD: [11, 85010100, 85010300],
} as const;

export const COLONY_FUNCTION_IDS = {
  COLONY_CENTRAL: 1,
  CREW_TRAINING_CENTRAL: 2,
  AIRFIELD: 4,
  FIGHTER_SHIPYARD: 5,
  SHIPYARD_SMALL: 6,
  SHIPYARD_MEDIUM: 7,
  SHIPYARD_LARGE: 8,
  TORPEDO_FAB: 9,
  MODULEFAB_TYPE1_LVL1: 10,
  MODULEFAB_TYPE1_LVL2: 11,
  MODULEFAB_TYPE1_LVL3: 12,
  MODULEFAB_TYPE2_LVL1: 13,
  MODULEFAB_TYPE2_LVL2: 14,
  MODULEFAB_TYPE2_LVL3: 15,
  MODULEFAB_TYPE3_LVL1: 16,
  MODULEFAB_TYPE3_LVL2: 17,
  MODULEFAB_TYPE3_LVL3: 18,
  ACADEMY: 20,
  SHIPYARD_XL: 21,
  REPAIR_STATION: 22,
  WAREHOUSE: 23,
  SHIELD_GENERATOR: 24,
  SHIELD_BATTERY: 25,
  ENERGY_PHALANX: 26,
  PARTICLE_PHALANX: 27,
  ANTI_PARTICLE: 28,
  FABRICATION_SUPPORT_LVL1: 29,
  FABRICATION_SUPPORT_LVL2: 30,
  UNDERGROUND_LOGISTICS: 31,
} as const;

export const COLONY_FUNCTION_GROUPS = {
  AIRFIELD: [COLONY_FUNCTION_IDS.AIRFIELD],
  FIGHTER_SHIPYARD: [COLONY_FUNCTION_IDS.FIGHTER_SHIPYARD],
  SHIPYARD: [
    COLONY_FUNCTION_IDS.FIGHTER_SHIPYARD,
    COLONY_FUNCTION_IDS.SHIPYARD_SMALL,
    COLONY_FUNCTION_IDS.SHIPYARD_MEDIUM,
    COLONY_FUNCTION_IDS.SHIPYARD_LARGE,
    COLONY_FUNCTION_IDS.SHIPYARD_XL,
  ],
  FABRICATION: [
    COLONY_FUNCTION_IDS.TORPEDO_FAB,
    COLONY_FUNCTION_IDS.MODULEFAB_TYPE1_LVL1,
    COLONY_FUNCTION_IDS.MODULEFAB_TYPE1_LVL2,
    COLONY_FUNCTION_IDS.MODULEFAB_TYPE1_LVL3,
    COLONY_FUNCTION_IDS.MODULEFAB_TYPE2_LVL1,
    COLONY_FUNCTION_IDS.MODULEFAB_TYPE2_LVL2,
    COLONY_FUNCTION_IDS.MODULEFAB_TYPE2_LVL3,
    COLONY_FUNCTION_IDS.MODULEFAB_TYPE3_LVL1,
    COLONY_FUNCTION_IDS.MODULEFAB_TYPE3_LVL2,
    COLONY_FUNCTION_IDS.MODULEFAB_TYPE3_LVL3,
  ],
  FABRICATION_SUPPORT: [
    COLONY_FUNCTION_IDS.FABRICATION_SUPPORT_LVL1,
    COLONY_FUNCTION_IDS.FABRICATION_SUPPORT_LVL2,
  ],
  DEFENSE: [
    COLONY_FUNCTION_IDS.SHIELD_GENERATOR,
    COLONY_FUNCTION_IDS.SHIELD_BATTERY,
    COLONY_FUNCTION_IDS.ENERGY_PHALANX,
    COLONY_FUNCTION_IDS.PARTICLE_PHALANX,
    COLONY_FUNCTION_IDS.ANTI_PARTICLE,
  ],
  ACADEMY: [COLONY_FUNCTION_IDS.ACADEMY],
  CENTRAL_CREW_TRAINING: [
    COLONY_FUNCTION_IDS.COLONY_CENTRAL,
    COLONY_FUNCTION_IDS.CREW_TRAINING_CENTRAL,
  ],
  UNDERGROUND_LOGISTICS: [COLONY_FUNCTION_IDS.UNDERGROUND_LOGISTICS],
} as const;

export const COLONY_BUILDING_ID_SETS = {
  HEADQUARTERS: new Set<number>(COLONY_BUILDING_IDS.HEADQUARTERS),
  LEGACY_SHIPYARD: new Set<number>(COLONY_BUILDING_IDS.LEGACY_SHIPYARD),
} as const;

export const COLONY_FUNCTION_ID_SETS = {
  SHIPYARD: new Set<number>(COLONY_FUNCTION_GROUPS.SHIPYARD),
  DEFENSE: new Set<number>(COLONY_FUNCTION_GROUPS.DEFENSE),
} as const;
